// ─── Mock Data ───────────────────────────────────────────────────────────────
export const MOCK_CHALLENGES = [
  {
    id: 'ch-001',
    department_id: 'dept-001',
    title: 'AI-Powered Smart Waste Management',
    description: 'Develop an IoT + AI solution for dynamic waste collection routing in urban areas, reducing operational costs by 40% while improving coverage.',
    pilot_budget: 2500000,
    status: 'ACTIVE',
    tags: ['IoT', 'AI/ML', 'Smart City'],
    applications: 12,
    match_count: 4,
    created_at: '2026-07-15T10:00:00Z',
  },
  {
    id: 'ch-002',
    department_id: 'dept-001',
    title: 'Pothole Detection & Road Quality Monitoring',
    description: 'Deploy a computer vision system on civic vehicles to automatically detect, classify, and geotag road defects for prioritized repair scheduling.',
    pilot_budget: 1800000,
    status: 'ACTIVE',
    tags: ['Computer Vision', 'GIS', 'Infrastructure'],
    applications: 8,
    match_count: 6,
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'ch-003',
    department_id: 'dept-001',
    title: 'Citizen Grievance Resolution Chatbot',
    description: 'Build a multilingual NLP chatbot integrated with the government ticketing system to auto-route and resolve citizen complaints with 72-hour SLA.',
    pilot_budget: 950000,
    status: 'REVIEW',
    tags: ['NLP', 'Chatbot', 'Governance'],
    applications: 23,
    match_count: 9,
    created_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'ch-004',
    department_id: 'dept-002',
    title: 'Predictive Analytics for Water Leakage Detection',
    description: 'Leverage sensor data and ML models to predict pipe failures and water leakage points before they occur, minimizing water loss in distribution networks.',
    pilot_budget: 3200000,
    status: 'ACTIVE',
    tags: ['Predictive ML', 'IoT', 'Water Management'],
    applications: 5,
    match_count: 3,
    created_at: '2026-08-01T10:00:00Z',
  },
];

export const MOCK_STARTUPS = [
  {
    id: 'st-001',
    company_name: 'NeoUrban Tech Pvt. Ltd.',
    dpiit_id: 'DIPP12345',
    tech_stack: ['React', 'Python', 'TensorFlow', 'IoT'],
    capability_statement: 'We build AI-first smart city solutions with proven deployments across 3 municipal corporations.',
    verified_status: true,
    match_score: 0.94,
    founded: 2021,
    team_size: 28,
  },
  {
    id: 'st-002',
    company_name: 'GreenRoute Analytics',
    dpiit_id: 'DIPP67890',
    tech_stack: ['Python', 'FastAPI', 'PostgreSQL', 'ML'],
    capability_statement: 'Specialized in waste management optimization and route analytics for tier-2 cities.',
    verified_status: true,
    match_score: 0.89,
    founded: 2020,
    team_size: 14,
  },
  {
    id: 'st-003',
    company_name: 'CivicSense AI',
    dpiit_id: 'DIPP11223',
    tech_stack: ['Computer Vision', 'Edge AI', 'GCP'],
    capability_statement: 'Computer vision specialists for civic infrastructure monitoring and automated reporting.',
    verified_status: false,
    match_score: 0.82,
    founded: 2022,
    team_size: 9,
  },
];

export const MOCK_MILESTONES = [
  {
    id: 'ms-001',
    challenge_id: 'ch-001',
    startup_id: 'st-001',
    milestone_title: 'POC Deployment & IoT Integration',
    payout_amount: 750000,
    kpi_criteria: { coverage: '5 wards', uptime: '99%', routes_optimized: 20 },
    status: 'COMPLETED',
    completed_at: '2026-07-30T00:00:00Z',
    challenge_title: 'AI-Powered Smart Waste Management',
    startup_name: 'NeoUrban Tech Pvt. Ltd.',
  },
  {
    id: 'ms-002',
    challenge_id: 'ch-001',
    startup_id: 'st-001',
    milestone_title: 'Pilot Scale-up to 20 Wards',
    payout_amount: 1000000,
    kpi_criteria: { coverage: '20 wards', cost_reduction: '30%', citizen_satisfaction: '4.0/5' },
    status: 'IN_PROGRESS',
    completed_at: null,
    challenge_title: 'AI-Powered Smart Waste Management',
    startup_name: 'NeoUrban Tech Pvt. Ltd.',
  },
  {
    id: 'ms-003',
    challenge_id: 'ch-002',
    startup_id: 'st-003',
    milestone_title: 'Computer Vision Model Training',
    payout_amount: 540000,
    kpi_criteria: { accuracy: '92%', potholes_detected: 500, false_positives: '<5%' },
    status: 'REVIEW',
    completed_at: null,
    challenge_title: 'Pothole Detection & Road Quality Monitoring',
    startup_name: 'CivicSense AI',
  },
  {
    id: 'ms-004',
    challenge_id: 'ch-003',
    startup_id: 'st-002',
    milestone_title: 'Chatbot MVP & Language Model Fine-tuning',
    payout_amount: 285000,
    kpi_criteria: { languages: 4, resolution_rate: '70%', avg_response_time: '<30s' },
    status: 'PENDING',
    completed_at: null,
    challenge_title: 'Citizen Grievance Resolution Chatbot',
    startup_name: 'GreenRoute Analytics',
  },
  {
    id: 'ms-005',
    challenge_id: 'ch-004',
    startup_id: 'st-001',
    milestone_title: 'Sensor Network Deployment',
    payout_amount: 960000,
    kpi_criteria: { sensors_deployed: 200, data_accuracy: '95%', network_uptime: '98%' },
    status: 'PENDING',
    completed_at: null,
    challenge_title: 'Predictive Analytics for Water Leakage',
    startup_name: 'NeoUrban Tech Pvt. Ltd.',
  },
];
